### ISSUE TITLE
Messages of Nudged (拍一拍) Cause Errors

### ISSUE THREAD

**Issue by zzc-tongji** [wechaty/wechaty-puppet-puppeteer#122]
### Description

- Receiving messages of nudged (拍一拍) causes errors.
- However, it will not terminate Wechaty process.

### Environments

- Wechaty 0.40.10
- wechaty-puppet-puppeteer (default)
- Node.js v12.16.2
- Windows 10, 1909, 18363

### Log

```
(node:2596) UnhandledPromiseRejectionWarning: Error: not found
    at PuppetPuppeteer.<anonymous> ([path]node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\src\puppet-puppeteer.ts:998:13)
    at Generator.next (<anonymous>)
    at fulfilled ([path]node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:23:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, 
promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zzc-tongji** [comment]
It should return a new message type (even not supported) rather than throw exception.

**Comment by zzc-tongji** [comment]
I have located the bug

``` js
bot.on('message', (m) => {
  const one = m.from();
  const room = m.room();
  if (room) {
    room.alias(one).then((data) => {
      // get sender's alias in room
    }).catch((error) => {
      // nudge (拍一拍) message causes error
    })
  }
});
```

**Comment by huan** [comment]
Good catch, and thank you very much for pointing out where the problem is!
